Fix: replace deprecated a11y_attrs_heading usage (refs #67)
adaptlearning/adapt-contrib-tutor pull request #76
Opened 2022-07-28 13:13 UTC by chris-steele

https://github.com/adaptlearning/adapt-contrib-tutor/compare/issue/67

### Fix
* Replace deprecated a11y_attrs_heading usage

[//]: # (Mention any other dependencies)
https://github.com/adaptlearning/adapt-contrib-core/issues/202

2022-07-28 13:54 UTC, oliverfoster requested changes

2022-07-28 13:54 UTC, oliverfoster commented on templates/tutor.hbs
> +        <div class="tutor__title-inner" role="heading" aria-level="{{a11y_aria_level _attributes.data-adapt-id '@component+1' _ariaLevel }}">
Can you add `_id: parentModel.get('_id'),` in here:
https://github.com/adaptlearning/adapt-contrib-tutor/blob/248bc0f948a027b0e398ad0ad3faf5998edbadc9/js/TutorModel.js#L19-L27

and change this to `_id` just to match the core pr?

```suggestion
        <div class="tutor__title-inner" role="heading" aria-level="{{a11y_aria_level _id '@component+1' _ariaLevel }}">
```

2022-07-28 15:20 UTC, oliverfoster approved these changes

2022-07-28 15:32 UTC, cahirodoherty-learningpool approved these changes
👀

2022-07-29 12:41 UTC, guywillis approved these changes
👀

2022-08-01 09:24 UTC, merged